language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=alpine

before_script:
  - make image DOCKERFILE=$Dockerfile VERSION=test

script:
  - make test DOCKERFILE=$Dockerfile VERSION=test

notifications:
  email:
    on_success: never
    on_failure: always
